# -*- coding: utf-8 -*-
"""Tarea01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvvgmigkmCHoOYk67sw8cLBU9HeMuHnH
"""

vaule= int(input("Ingrese un numero: "))
if ((vaule%2)==0):
  print("Es un numero par")
else:
  print("No es numero par")

cadena=input("Ingrese una cadena de caracteres")
repeticion=int(input("Ingrese la veces que se repetira"))
i=0
while(i<repeticion):
  print(cadena)
  i+=1

numDeHora=float(input("Ingrese el numero de horas que laboro al dia: "))
periodo=int(input("Ingrese el periodo de tiempo que se laboro \n1.-1 dia\n2.-1 semana\n3.-1 mes\n"))
def pago(numDeHora,periodo):
  costo=150
  if(periodo==1):
    pago=costo*numDeHora*1
    return pago
  if(periodo==2):
    pago=costo*numDeHora*5
    return pago
  if(periodo==3):
    pago=costo*numDeHora*20
    return pago

print ("Su pago sera de: ",pago(numDeHora,periodo))

print("a.suma\nb.resta\nc.multiplicacio\nd.division")
escoge=input("Introduzca una opcion:")
if(escoge=='a'):
  print("Suma")
  x=float(input("Ingrese un numero: "))
  y=float(input("Ingrese otro numero: "))
  print(x+y)

if(escoge=='b'):
  print("Resta")
  x=float(input("Ingrese un numero: "))
  y=float(input("Ingrese otro numero: "))
  print(x-y)

if(escoge=='c'):
  print("Multiplicacion")
  x=float(input("Ingrese un numero: "))
  y=float(input("Ingrese otro numero: "))
  print(x*y)

if(escoge=='d'):
  print("Division")
  x=float(input("Ingrese un numero: "))
  y=0 
  while (y==0):
    y=float(input("Ingrese otro numero: "))
  print(x/y)

payasos=int (input("Ingrese el numero de payasos: "))
juegos=int (input ("Ingrese el numero de juegos de mesa: "))
def muestra(payasos,juegos):  
  peso=(payasos*.17)+(juegos*.15)
  if (peso>10):
   print("ERROR\nEl peso se paso por ",peso-10,"kg")
  elif(peso<=10):
   print("El peso de su pedido es: ", peso,"kg")
print(muestra(payasos,juegos))

salario=float(input("Ingrese su salario: "))
def rango(salario):
  if(salario<10000):
    print("Menos de 10 mil\n Su salario neto es de: ",salario*.95)

  if(salario>10000 and salario<15000):
    print("Entre 10 mil y 15 mil\n Su salario neto es de: ",salario*.9)

  if(salario>15000 and salario<20000):
    print("Entre 15 mil y 20 mil\n Su salario neto es de: ",salario*.85)

  if(salario>20000):
    print("Mas de 20 mil\n Su salario neto es de: ",salario*.82)

print(rango(salario))

edad=int(input("Ingrese su edad: "))
print("a.-Estudiante con credencial\nb.Docente con credencial\nc.-INAPAM\nd.-Ninguna")
ocupacion=input("Ingrese su ocupacion: ")
print(costo(edad,ocupacion))
def costo(edad,ocupacion):
  if (edad<4):
    print("Gratis")

  if (edad>=4 and edad<=16):
    if(ocupacion=='a'):
      print(50*.9,"$")
    else:
      print("50$")

  if (edad>16):
    if (ocupacion=='a'):
      print(100*.9,"$")
    elif (ocupacion=='b'):
      print(100*.7,"$")
    elif (ocupacion=='c'):
      print(100*.5,"$")
    else:
      print("100$")

repeticion=int(input("Ingrse un numero"))
a=['*']
i=0
while(i<repeticion):
  print(a);
  a.append('*')
  i+=1

def calfactorial(factorial):
  i=factorial
  while (i<=factorial and i>1):
    factorial=factorial*(i-1)
    i=i-1
  return factorial

factorial=0
while (factorial<=0):
  factorial=int(input("Ingrese un numero:"))

print("El factorial es:",calfactorial(factorial))

def calArea(radio):
  area=(3.1416)*(pow(radio,2)) 
  return area
def calVolumen(altura):
  volumen=calArea(radio)*altura 
  return volumen

radio=float(input("Ingrese el valor del radio: "))
altura=float(input("Ingresa el valor de la altura: "))

print("El area es: ",calArea(radio))
print("El volumen es: ",calVolumen(altura))